export const PALABRAS = [
    'aboya', 'abran', 'abras', 'acles', 'acoja', 'acojo', 'acres', 'actas', 'actos', 'acuna', 'acune', 'acuno', 'acuso', 'acuña', 'acuñe', 'acuño', 'afeas', 'aguda', 'agudo', 'albas', 'albos', 'alces', 'algas', 'almas', 'alojo', 'altas', 'altos', 'alías', 'amina', 'ancas', 'andas', 'andes', 'anima', 'aojar', 'aojas', 'aojos', 'apoda', 'apodo', 'arces', 'arcos', 'ardan', 'ardas', 'ardes', 'arias', 'arios', 'arlos', 'armes', 'arpas', 'artes', 'aruñe', 'aruño',
    'ascos', 'asees', 'aseos', 'asolo', 'atoja', 'atojo', 'avara', 'bagas', 'bajas', 'balas', 'bales', 'bares', 'barre', 'basca', 'baste', 'batas', 'bates', 'bayas', 'bañas', 'bañes', 'baños', 'bebed', 'bebes', 'besen', 'beses', 'besos', 'betas', 'bodas', 'bogad', 'bogas', 'bogue', 'bojar', 'bojas', 'bojos', 'bolar', 'bondi', 'bonos', 'borre', 'botan', 'botas', 'boten', 'botes', 'boyas', 'bramo', 'bruta', 'bruño', 'bulas', 'buses', 'caceo', 'cagas',
    'cajas', 'calce', 'cales', 'callo', 'calme', 'calmo', 'canas', 'canes', 'cansa', 'capas', 'capes', 'capta', 'capto', 'caros', 'casan', 'casas', 'casca', 'casos', 'catas', 'causa', 'cavas', 'cavos', 'cazan', 'cazas', 'cazos', 'cañas', 'cañeo', 'cebos', 'ceded', 'cedes', 'cefos', 'cejas', 'celes', 'cenas', 'cepas', 'ceras', 'cerdo', 'ceros', 'ciega', 'cines', 'clamo', 'Clara', 'clava', 'clubs', 'coces', 'codeo', 'coged', 'cogen', 'coger', 'coges', 'cojas',
    'cojos', 'colas', 'coles', 'colma', 'coman', 'comas', 'comed', 'comes', 'conos', 'copas', 'copos', 'copta', 'coral', 'coras', 'corea', 'corra', 'corre', 'corro', 'corsa', 'cosas', 'coses', 'creas', 'crees', 'creme', 'cremo', 'croar', 'cruje', 'cubas', 'cubos', 'cucos', 'cuida', 'cuide', 'culos', 'culta', 'cunas', 'cural', 'curas', 'curdo', 'cures', 'curio', 'cuñas', 'dagas', 'datos', 'dañes', 'daños', 'debas', 'debed', 'debes', 'dedos', 'dejas', 'densa',
    'dijes', 'diles', 'doman', 'domas', 'domes', 'domos', 'donan', 'donas', 'donen', 'dones', 'dores', 'doria', 'dorio', 'dotas', 'dotes', 'doñas', 'drupa', 'dudan', 'dunas', 'dures', 'duros', 'echas', 'eches', 'echos', 'edita', 'eleve', 'ellos', 'emana', 'emoji', 'enoja', 'enojo', 'entes', 'erizo', 'errar', 'erres', 'estad', 'estas', 'euros', 'evita', 'falle', 'falos', 'feria', 'fetos', 'ficad', 'ficas', 'fijas', 'filas', 'files', 'fique', 'focos', 'folia',
    'forma', 'fosos', 'fotos', 'frita', 'fugas', 'gafas', 'galas', 'galos', 'ganes', 'gases', 'gatos', 'genes', 'gimen', 'gimes', 'giras', 'giros', 'godas', 'godos', 'goles', 'gordo', 'gorra', 'grabe', 'grave', 'grite', 'groar', 'habas', 'hacen', 'haces', 'hagan', 'hagas', 'halan', 'halas', 'hallo', 'halos', 'harte', 'hayan', 'hayas', 'heces', 'hecha', 'hecho', 'hemos', 'hiero', 'hijas', 'hilan', 'hilos', 'hinca', 'hipos', 'hoces', 'hojas', 'huera', 'huero',
    'hunas', 'hunos', 'hurgo', 'husos', 'ibais', 'ideas', 'intis', 'isbas', 'islas', 'jalan', 'jefes', 'jerga', 'jodas', 'jodes', 'joyas', 'joyel', 'jugos', 'jujeo', 'jures', 'kanes', 'kunas', 'kurda', 'labes', 'labia', 'labre', 'lacra', 'lacta', 'lados', 'ladro', 'lagos', 'lamas', 'lamen', 'lames', 'lapas', 'larga', 'latas', 'laves', 'laxas', 'laxos', 'lazan', 'lazos', 'legas', 'legos', 'lejos', 'lemas', 'lenta', 'levas', 'leves', 'leyes',
    'libia', 'lides', 'limas', 'linda', 'liras', 'lises', 'locas', 'locha', 'locos', 'lomos', 'lores', 'loros', 'losas', 'loteo', 'lozas', 'luces', 'luche', 'lucho', 'lunas', 'lusas', 'lusos', 'maceo', 'magos', 'malas', 'males', 'malos', 'mamas', 'manas', 'manca', 'manda', 'manos', 'mapas', 'mares', 'marro', 'masco', 'mases', 'matas', 'mates', 'mayas', 'mazos', 'mañas', 'meaba', 'mecen', 'meces', 'menes', 'meras', 'meros', 'mesas', 'mesen', 'meses', 'metas',
    'metes', 'mezas', 'midas', 'migro', 'miles', 'minas', 'mines', 'miras', 'miren', 'mires', 'misad', 'misas', 'misma', 'mista', 'mitos', 'mitro', 'mocos', 'modas', 'modos', 'mofes', 'mojar', 'mojas', 'mojen', 'mojos', 'molas', 'moles', 'monas', 'monos', 'mopas', 'moras', 'mores', 'moros', 'morro', 'moved', 'mozas', 'moños', 'mucas', 'mucos', 'mudas', 'mudos', 'mueve', 'mugen', 'muges', 'mugid', 'mujan', 'mujas', 'mulas', 'muros', 'nabos', 'naces',
    'nadas', 'nades', 'narre', 'naves', 'nazis', 'necia', 'netos', 'niños', 'nomos', 'notas', 'notes', 'nubes', 'nucas', 'nudas', 'nudos', 'nulas', 'nulos', 'obras', 'odias', 'odios', 'ogros', 'ollas', 'ondas', 'onzas', 'opera', 'optas', 'orbes', 'orcas', 'orden', 'ornan', 'oseas', 'otras', 'ovulo', 'pacas', 'pacen', 'pacta', 'pagan', 'pague', 'pajas', 'pajes', 'palas', 'palme', 'palos', 'palpa', 'panes', 'paras', 'parda', 'paren', 'pares', 'parta', 'pasas',
    'pasen', 'pases', 'patas', 'patea', 'patos', 'pañal', 'pecas', 'peces', 'pedos', 'pegas', 'pegue', 'pelos', 'penas', 'penda', 'pende', 'penes', 'peras', 'peros', 'pesad', 'pesas', 'pesen', 'peses', 'pesos', 'petas', 'peñas', 'pican', 'pidas', 'pides', 'pines', 'pipas', 'pisad', 'pises', 'plena', 'pleno', 'pocas', 'pocos', 'podas', 'poded', 'poder', 'podes', 'poned', 'ponen', 'poner', 'pones', 'ponga', 'porfa', 'posee', 'posen', 'poses',
    'posos', 'potos', 'poyas', 'pozos', 'prado', 'preña', 'preño', 'pueda', 'puede', 'puedo', 'pujan', 'pujas', 'pujen', 'pulen', 'pumas', 'puras', 'puros', 'queme', 'quemo', 'quise', 'quiso', 'quito', 'rabos', 'ralbe', 'ramos', 'ranas', 'rapas', 'rasas', 'rasco', 'ratas', 'ratos', 'razas', 'reces', 'recia', 'redes', 'rejas', 'remas', 'remes', 'remos', 'rento', 'reses', 'reste', 'retes', 'retos', 'reyes', 'rezan', 'rezas', 'rices', 'rifas', 'rimas', 'rimen',
    'rimes', 'rinda', 'roban', 'robes', 'rocas', 'rodas', 'rojas', 'rojos', 'rolla', 'romas', 'romos', 'rompe', 'rones', 'rotas', 'rotos', 'rotás', 'royas', 'royos', 'rudos', 'rugen', 'ruges', 'rujan', 'runas', 'rusas', 'rusos', 'ruñas', 'sabia', 'sacan', 'sacas', 'sacos', 'salga', 'salgo', 'salta', 'salva', 'salve', 'sanad', 'sanas', 'sapos', 'sañas', 'sebos', 'secan', 'sedes', 'sepas', 'seres', 'seria', 'setas', 'siega', 'siego', 'sigan', 'siria', 'siseo',
    'soban', 'sobas', 'sobes', 'sogas', 'soles', 'sonad', 'sonar', 'sorbe', 'soñad', 'soñar', 'subas', 'subes', 'sucia', 'sucre', 'sudan', 'sudar', 'sudas', 'suela', 'suele', 'suena', 'suene', 'sueno', 'sueña', 'sueñe', 'sueño', 'suiza', 'sumas', 'sushi', 'tacos', 'talas', 'tapas', 'tapes', 'tejas', 'temas', 'temen', 'temes', 'tened', 'tenga', 'tengo', 'tenia', 'tensa', 'terca', 'tersa', 'terse', 'testo', 'tetar', 'tetas', 'tiene', 'times', 'tipos', 'tiras',
    'tiros', 'togas', 'tomad', 'toman', 'tomas', 'tomes', 'tonos', 'tonto', 'topas', 'topos', 'torpe', 'tosed', 'traed', 'traen', 'traer', 'traes', 'trajo', 'tubos', 'tunas', 'untes', 'urdas', 'urnas', 'usaos', 'usate', 'uñoso', 'vacan', 'vacas', 'vagas', 'vagos', 'vague', 'vales', 'valga', 'valgo', 'valsa', 'valse', 'vamos', 'vasca', 'vasos', 'vasta', 'vates', 'vayan', 'vayas', 'veces', 'vedas', 'velas', 'veles', 'velos', 'vemos', 'venas', 'vengo', 'vente',
    'vetas', 'vidas', 'viene', 'viera', 'vigas', 'vinos', 'vires', 'voces', 'volar', 'votad', 'votan', 'votar', 'votas', 'voten', 'votos', 'wikis', 'wones', 'yates', 'yemas', 'yendo', 'yenes', 'yesca', 'yogur', 'yugos', 'zacas', 'zarca', 'zares', 'zetas', 'zonas', 'zorro', 'zurda', 'zurro',
    'anido','pasta','norte','ritos','sabio','salas','bolsa','balsa','pilas','olivo','tomar','tarta','muela','multa','mirar','agota','litro','bueno','perro','robar','corta','corto','lamer','hueco','cueva','patio','flojo','matar','pieza','fruta','rosas','carro','anida','latir','hielo','tirar','tizas','queso','curso','polos','valla','manta','letra','lucha','vocal','denso','tarro','busto','porte','poste','meter','pudor','pilar','casco','torno','torso','barra','barro','minar','telar','tapia','pitar','pelar','doler','gotas','rigor','termo','barco','barca','rezar','venta','hurto','larva','amigo','calor','rubia','color','sanar','labor','toros','tabla','marca','alado','ramas','ahora','marco','carga','vuela','carne','pollo','campo','rodar','robos','rollo','terco','dardo','pulpo','cosen','coser','borde','verbo','verso','estar','corte','enano','limar','lijar','ligar','prisa','brisa','valor','tener','resta','plazo','plato','plano','plata','cerca'
];